version: 0.1

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "eu-west-2"

phases:
  install:
    commands:
      - git clone https://github.com/photobox/pbx-group-security.git
      - curl -Ls https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.tar.gz -o ./hugo.tar.gz
      - tar xf ./hugo.tar.gz
      - mv hugo /usr/bin/
      - hugo version
  build:
    commands:
      - cd pbx-group-security && hugo
  post_build:
    commands:
      - cd pbx-group-security && pwd
      - cd pbx-group-security && ls public
      - cd pbx-group-security && aws s3 sync --acl "public-read" --sse "AES256" public/ s3://pbx-group-security.com-cdn --exclude 'post'
      - aws configure set preview.cloudfront true
      - aws cloudfront create-invalidation --distribution-id E3K53GHHL4D0LE --paths /index.html / /page/*
