version: 0.1

environment_variables:
  plaintext:
    AWS_DEFAULT_REGION: "eu-west-2"

phases:
  install:
    commands:
      - ls
      - pwd
      - curl -Ls https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.tar.gz -o ./hugo.tar.gz
      - ls
      - tar xf ./hugo.tar.gz -C /tmp
      - ls
  build:
    commands:
      - hugo
  post_build:
    commands:
      ls